//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceMonitor.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitorProduct
    {
        public int MonitorID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> WebsiteID { get; set; }
        public System.DateTime DateMonitored { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Product Product { get; set; }
        public virtual Website Website { get; set; }
    }
}
