//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceMonitor.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PriceMonitorEntities : DbContext
    {
        public PriceMonitorEntities()
            : base("name=PriceMonitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<MonitorProduct> MonitorProducts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Website> Websites { get; set; }
        public virtual DbSet<ProductsObtainedView> ProductsObtainedViews { get; set; }
        public virtual DbSet<MonitoredProductsView> MonitoredProductsViews { get; set; }
        public virtual DbSet<Search> Searches { get; set; }
    }
}
