//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceMonitor.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsObtainedView
    {
        public string Product_Title { get; set; }
        public decimal Subtotal { get; set; }
        public Nullable<decimal> Shipping { get; set; }
        public string URL { get; set; }
        public string Website { get; set; }
        public string Category { get; set; }
        public string SearchTerm { get; set; }
    }
}
